version: "3"
services:

  cooperativa_db:
    image: postgres:12-alpine
    container_name: cooperativa_db
    restart: always
    environment:
      - POSTGRES_DB=cooperativa_bd
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
    ports:
      - 5432:5432
    networks:
      - localnetwork
networks:
  localnetwork:
    driver: bridge